Repository likelion-ssu/lion-s-study, pull requests merged in 2025-03, with the labels that each got.

#2 Chore: 프로젝트 세팅 및 prettier, esLint 설정
  .gitignore
  .prettierignore
  .prettierrc
  README.md
  eslint.config.mjs
  next.config.ts
  package.json
  pnpm-lock.yaml
  src/app/favicon.ico
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  tsconfig.json
Labels: ❗️First Issue

#4 Chore : global style 지정과 폰트 설정
  next.config.mjs
  package.json
  public/fonts/PretendardVariable.woff2
  src/app/layout.tsx
  src/app/page.tsx
  src/app/styles/globals.css
  src/app/styles/reset.css
Labels: 🎨Style

#6 Chore : svgr 세팅 및 폴더구조 세팅
  next.config.mjs
  package.json
  pnpm-lock.yaml
  src/app/(common-layout)/main/page.tsx
  src/app/(common-layout)/studyroom/page.tsx
  src/assets/icon/title.svg
  src/types/svg.d.ts
  tsconfig.json
Labels: ❗️First Issue

#8 chore: 파일 구조 세팅 수정
  src/app/(common-layout)/article/page.tsx
  src/app/(common-layout)/layout.tsx
  src/app/(common-layout)/main/page.tsx
  src/app/page.tsx
Labels: 🎸 기타, ❗️First Issue

#10 Feat : 아티클 생성 모달 퍼블리싱
  src/app/(common-layout)/article/page.tsx
  src/app/_component/article/AddArticleModal.module.css
  src/app/_component/article/AddArticleModal.tsx
  src/app/_component/article/ArticleEditor.module.css
  src/app/_component/article/ArticleEditor.tsx
  src/app/_component/article/EditorBlock.module.css
  src/app/_component/article/EditorBlock.tsx
  src/app/_component/article/ShowArticle.module.css
  src/app/_component/article/ShowArticle.tsx
  src/app/_component/article/Titlebox.module.css
  src/app/_component/article/Titlebox.tsx
  src/assets/icon/delete.svg
  src/constants/EditorBlockList.ts
Labels: 💡Feature

#13 Feat : studyroom layout
  src/app/(common-layout)/studyroom/page.tsx
  src/app/_component/studyroom/Article.module.css
  src/app/_component/studyroom/Article.tsx
  src/app/_component/studyroom/CommonStyles.module.css
  src/app/_component/studyroom/CommonTitle.tsx
  src/app/_component/studyroom/Link.module.css
  src/app/_component/studyroom/Link.tsx
  src/app/_component/studyroom/Notice.module.css
  src/app/_component/studyroom/Notice.tsx
  src/app/_component/studyroom/StudyroomMain.module.css
  src/app/_component/studyroom/StudyroomMain.tsx
  src/app/_component/studyroom/StudyroomTitle.module.css
  src/app/_component/studyroom/StudyroomTitle.tsx
  src/app/styles/globals.css
  src/assets/icon/arrow_right.svg
  src/assets/icon/heart.svg
  src/assets/icon/link.svg
  src/assets/icon/share.svg
Labels: 💡Feature

#14 Feat : 아티클 읽기 모달 퍼블리싱
  src/app/(common-layout)/article/page.tsx
  src/app/_component/addarticle/AddArticleModal.module.css
  src/app/_component/addarticle/AddArticleModal.tsx
  src/app/_component/addarticle/ArticleEditor.module.css
  src/app/_component/addarticle/ArticleEditor.tsx
  src/app/_component/addarticle/EditorBlock.module.css
  src/app/_component/addarticle/EditorBlock.tsx
  src/app/_component/addarticle/ShowArticle.module.css
  src/app/_component/addarticle/ShowArticle.tsx
  src/app/_component/addarticle/Titlebox.module.css
  src/app/_component/addarticle/Titlebox.tsx
  src/app/_component/readArticle/ReadArticleModal.module.css
  src/app/_component/readArticle/ReadArticleModal.tsx
Labels: 💡Feature
