Repository likelion-ssu/lion-s-study, pull requests merged in 2025-04, with the labels that each got.

#17 Feat: 로그인 기능 구현
  package.json
  pnpm-lock.yaml
  src/app/(common-layout)/page.tsx
  src/app/_component/common/Modal.module.css
  src/app/_component/common/Modal.tsx
  src/app/_component/common/PlusBtn.module.css
  src/app/_component/common/PlusBtn.tsx
  src/app/_component/domain/login/GoogleLogin.module.css
  src/app/_component/domain/login/GoogleLoginBtn.tsx
  src/app/_component/domain/login/LoginBtn.module.css
  src/app/_component/domain/login/LoginBtn.tsx
  src/app/_component/domain/login/NameBtn.module.css
  src/app/_component/domain/login/NameBtn.tsx
  src/app/_component/domain/login/UserBtn.tsx
  src/app/_component/domain/login/modal/LoginModalContent.tsx
  src/app/_component/domain/login/modal/LogoutModal.module.css
  src/app/_component/domain/login/modal/LogoutModalContent.tsx
  src/app/_component/domain/login/modal/SignUpModal.module.css
  src/app/_component/domain/login/modal/SignUpModalContent.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/styles/globals.css
  src/assets/icon/google_logo.svg
  src/firebase/firebaseAuth.ts
  src/firebase/firebasedb.ts
  src/firebase/firestore.ts
  src/hooks/useAuth.ts
  src/hooks/useHydration.ts
  src/hooks/useIsMounted.ts
  src/store/useModalStore.ts
  src/store/useUserStore.ts
Labels: 💡Feature

#21 Refactor: 불필요한 연산 방지
  src/app/_component/domain/login/GoogleLoginBtn.tsx
Labels: 🛠️Refactor

#24 Style: TopBar 컴포넌트 작업
  src/app/(common-layout)/layout.tsx
  src/app/(common-layout)/members/page.tsx
  src/app/(common-layout)/page.tsx
  src/app/_component/common/TopBar.module.css
  src/app/_component/common/TopBar.tsx
  src/app/_component/common/topbarMenu/LogoBtn.module.css
  src/app/_component/common/topbarMenu/LogoBtn.tsx
  src/app/_component/common/topbarMenu/MembersBtn.module.css
  src/app/_component/common/topbarMenu/MembersBtn.tsx
  src/app/_component/domain/login/UserBtn.module.css
  src/app/_component/domain/login/UserBtn.tsx
  src/assets/image/lion_logo.png
Labels: 🎨Style

#26 Feat: 사자의 서재 메인 페이지 구현
  cors.json
  src/app/(common-layout)/page.module.css
  src/app/(common-layout)/page.tsx
  src/app/_component/common/TopBar.module.css
  src/app/_component/domain/main/AddBtn.module.css
  src/app/_component/domain/main/AddBtn.tsx
  src/app/_component/domain/main/AddStudyContent.module.css
  src/app/_component/domain/main/AddStudyContent.tsx
  src/app/_component/domain/main/StudyBtn.module.css
  src/app/_component/domain/main/StudyBtn.tsx
  src/app/_component/domain/main/StudySection.module.css
  src/app/_component/domain/main/StudySection.tsx
  src/assets/icon/main/empty_heart.svg
  src/assets/icon/main/fill_heart.svg
  src/assets/icon/main/small_delete.svg
  src/assets/icon/plus.svg
  src/assets/image/background_mask.png
  src/assets/image/default_thumbnail.png
  src/firebase/firebaseStorage.ts
  src/store/studyRoomStore.ts
  src/types/studyRooms/studyRoom.ts
  src/utils/formatDate.ts
Labels: 💡Feature

#33 Feat: Studyroom 퍼블리싱 마무리 및 클릭이벤트 연결
  src/app/(common-layout)/studyroom/[id]/page.tsx
  src/app/(common-layout)/studyroom/page.tsx
  src/app/_component/common/Modal.module.css
  src/app/_component/domain/main/StudyBtn.tsx
  src/app/_component/domain/main/StudySection.tsx
  src/app/_component/studyroom/AddSubContentBtn.tsx
  src/app/_component/studyroom/Article.tsx
  src/app/_component/studyroom/Link.tsx
  src/app/_component/studyroom/Notice.tsx
  src/app/_component/studyroom/StudyroomMain.module.css
  src/app/_component/studyroom/StudyroomMain.tsx
  src/app/_component/studyroom/StudyroomTitle.tsx
  src/app/_component/studyroom/modal/AddContent.module.css
  src/app/_component/studyroom/modal/AddLinkModalContent.tsx
  src/app/_component/studyroom/modal/AddNoticeModalContent.tsx
  src/constants/StudyroomContentType.ts
  src/store/useStudyroomDetailStore.ts
  src/types/studyRoomDetails/content.ts
  src/types/studyRooms/studyRoom.ts
Labels: 💡Feature

#36 Feat: article 작성 모달 파이어베이스 연동
  package.json
  src/app/(common-layout)/article/page.tsx
  src/app/_component/domain/addarticle/AddArticleModal.module.css
  src/app/_component/domain/addarticle/AddArticleModal.tsx
  src/app/_component/domain/addarticle/DeleteModal.module.css
  src/app/_component/domain/addarticle/DeleteModal.tsx
  src/app/_component/domain/addarticle/Titlebox.module.css
  src/app/_component/domain/addarticle/Titlebox.tsx
  src/app/_component/domain/addarticle/ToastEditor.tsx
  src/app/_component/domain/readArticle/ReadArticleModal.module.css
  src/app/_component/domain/readArticle/ReadArticleModal.tsx
Labels: 💡Feature

#38 Feat/studyroom firebase
  src/app/(common-layout)/studyroom/[id]/page.tsx
  src/app/_component/studyroom/Article.module.css
  src/app/_component/studyroom/Article.tsx
  src/app/_component/studyroom/CommonStyles.module.css
  src/app/_component/studyroom/Link.tsx
  src/app/_component/studyroom/Notice.module.css
  src/app/_component/studyroom/Notice.tsx
  src/app/_component/studyroom/StudyroomMain.module.css
  src/app/_component/studyroom/StudyroomMain.tsx
  src/app/_component/studyroom/StudyroomTitle.tsx
  src/hooks/useArticles.ts
  src/hooks/useLinks.ts
  src/hooks/useNotices.ts
  src/hooks/useStudyroomDetail.ts
  src/store/useStudyroomIdStore.ts
  src/types/studyRoomDetails/article.ts
  src/types/studyRoomDetails/link.ts
  src/types/studyRoomDetails/notice.ts
Labels: 💡Feature

#40 Feat: article id, studyroomId 관리, 마크다운 텍스트 추출 기능 구현
  package.json
  pnpm-lock.yaml
  src/app/(common-layout)/article/page.tsx
  src/app/_component/domain/addarticle/AddArticleModal.tsx
  src/app/_component/domain/addarticle/DeleteModal.tsx
  src/app/_component/domain/readArticle/ReadArticleModal.tsx
  src/hooks/useArticles.ts
Labels: 💡Feature

#41 Feat/studyroom firebase
  src/app/_component/common/Modal.module.css
  src/app/_component/studyroom/AddSubContentBtn.tsx
  src/app/_component/studyroom/Article.tsx
  src/app/_component/studyroom/Link.module.css
  src/app/_component/studyroom/Link.tsx
  src/app/_component/studyroom/Notice.tsx
  src/app/_component/studyroom/modal/AddLinkModalContent.tsx
  src/app/_component/studyroom/modal/AddNoticeModalContent.tsx
  src/hooks/useLinks.ts
  src/hooks/useNotices.ts
  src/types/studyRoomDetails/article.ts
  src/types/studyRoomDetails/itemClickHandler.ts
  src/types/studyRoomDetails/link.ts
  src/types/studyRoomDetails/notice.ts
Labels: 💡Feature, 🎨Style, 🛠️Refactor

#44 Feat: toast popup 컴포넌트 제작
  src/app/(common-layout)/article/page.tsx
  src/app/_component/common/Toast.module.css
  src/app/_component/common/Toast.tsx
  src/assets/icon/toast_green.svg
  src/assets/icon/toast_yellow.svg
  src/constants/EditorBlockList.ts
  src/constants/ToastTypeList.ts
Labels: 💡Feature

#48 Feat: 아티클 수정기능 및 아티클 관련 토스트 팝업 구현
  src/app/_component/common/Toast.tsx
  src/app/_component/domain/addarticle/AddArticleModal.tsx
  src/app/_component/domain/addarticle/DeleteModal.tsx
  src/app/_component/domain/addarticle/Titlebox.tsx
  src/app/_component/domain/addarticle/ToastEditor.tsx
  src/app/_component/domain/readArticle/ReadArticleModal.module.css
  src/app/_component/studyroom/Article.tsx
  src/app/_component/studyroom/StudyroomMain.tsx
  src/constants/ToastTypeList.ts
  src/store/useToastStore.ts
Labels: 💡Feature, 🛠️Refactor

#49 Feat : studyroom 삭제 modal 구현, 컨텐츠 정렬, 링크 복사 기능
  src/app/(common-layout)/studyroom/[id]/page.tsx
  src/app/_component/studyroom/AddSubContentBtn.tsx
  src/app/_component/studyroom/Article.tsx
  src/app/_component/studyroom/Link.tsx
  src/app/_component/studyroom/Notice.tsx
  src/app/_component/studyroom/StudyroomTitle.tsx
  src/app/_component/studyroom/modal/AddLinkContentModal.tsx
  src/app/_component/studyroom/modal/AddNoticeContentModal.tsx
  src/app/_component/studyroom/modal/DeleteContentModal.module.css
  src/app/_component/studyroom/modal/DeleteContentModal.tsx
  src/constants/StudyroomContentType.ts
  src/hooks/useArticles.ts
  src/hooks/useLinks.ts
  src/hooks/useNotices.ts
  src/utils/sortByCreatedAt.ts
Labels: 💡Feature, 🛠️Refactor, 🐞Bug

#54 Feat: 메인 화면 비로그인 유저 서재 접속 차단, 관심 설정 기능 추가
  package.json
  pnpm-lock.yaml
  src/app/(common-layout)/(private)/article/page.tsx
  src/app/(common-layout)/(private)/members/page.tsx
  src/app/(common-layout)/(private)/studyroom/[id]/page.tsx
  src/app/(common-layout)/(public)/page.module.css
  src/app/(common-layout)/(public)/page.tsx
  src/app/_component/common/Toast.tsx
  src/app/_component/common/topbarMenu/MembersBtn.tsx
  src/app/_component/domain/main/AddBtn.tsx
  src/app/_component/domain/main/StudyBtn.tsx
  src/app/_component/domain/main/StudySection.tsx
  src/app/_component/studyroom/StudyroomTitle.tsx
  src/assets/icon/heart_empty.svg
  src/constants/ToastTypeList.ts
  src/hooks/useFavorite.ts
  src/middleware.ts
  src/store/useUserStore.ts
  src/utils/checkAuth.ts
Labels: 💡Feature

#55 Feat : studyroom toast 추가
  src/app/_component/domain/main/StudySection.tsx
  src/app/_component/studyroom/Article.tsx
  src/app/_component/studyroom/modal/AddLinkContentModal.tsx
  src/app/_component/studyroom/modal/AddNoticeContentModal.tsx
  src/app/_component/studyroom/modal/DeleteContentModal.tsx
  src/hooks/useArticles.ts
  src/hooks/useLinks.ts
  src/hooks/useNotices.ts
  src/utils/sortArrByTime.ts
Labels: 💡Feature

#57 Style: Footer 퍼블리싱, 서재 제목 길 경우 ellipsis 처리, 메인 페이지 반응형 처리
  src/app/(common-layout)/(public)/page.module.css
  src/app/(common-layout)/layout.tsx
  src/app/_component/common/Footer.module.css
  src/app/_component/common/Footer.tsx
  src/app/_component/domain/main/StudyBtn.module.css
  src/app/_component/domain/main/StudySection.module.css
  src/app/_component/domain/main/StudySection.tsx
  src/app/styles/globals.css
Labels: 🎨Style

#58 Feat: favicon 및 open graph 추가
  public/og-image.png
  src/app/favicon.ico
  src/app/layout.tsx
Labels: 💡Feature

#62 feat : 예외상황 토스트 추가 및 1차 QA 반영
  src/app/_component/studyroom/StudyroomMain.tsx
  src/app/_component/studyroom/StudyroomTitle.tsx
  src/app/_component/studyroom/modal/AddLinkContentModal.tsx
  src/app/_component/studyroom/modal/AddNoticeContentModal.tsx
  src/app/_component/studyroom/modal/DeleteContentModal.tsx
Labels: 💡Feature, 🎨Style

#68 Fix: 모달 뒤로가기, 새로고침 방지
  src/app/_component/common/Modal.tsx
  src/app/_component/domain/addarticle/AddArticleModal.tsx
  src/constants/ToastTypeList.ts
  src/hooks/useConfirmBeforeRefresh.ts
Labels: 🐞Bug

#73 Feat: UI 항목 이슈 작업
  src/app/_component/domain/login/GoogleLoginBtn.tsx
  src/app/_component/domain/login/modal/LogoutModalContent.tsx
  src/app/_component/domain/login/modal/SignUpModalContent.tsx
  src/app/_component/domain/main/AddStudyContent.module.css
  src/app/_component/domain/main/AddStudyContent.tsx
  src/app/_component/domain/main/StudyBtn.module.css
  src/app/_component/studyroom/StudyroomMain.module.css
  src/constants/ToastTypeList.ts
  src/firebase/firebaseAuth.ts
Labels: 🎨Style, 🛠️Refactor
