Repository likelion-ssu/lion-s-study, pull requests merged in 2025-05, with the labels that each got.

#78 Fix: members 페이지 스타일 수정 및 document 안전 접근
  src/app/(common-layout)/(private)/members/page.module.css
  src/app/(common-layout)/(private)/members/page.tsx
  src/app/loading.tsx
  src/utils/checkAuth.ts
Labels: 🛠️Refactor, 🐞Bug

#70 fix : studyroom 유효성 확인 방식 수정
  src/app/_component/studyroom/StudyroomMain.tsx
Labels: 🐞Bug

#79 feat: 404페이지 제작
  src/app/(common-layout)/(private)/article/page.tsx
  src/app/not-found.tsx
  src/app/styles/not-found.module.css
Labels: 💡Feature

#82 Feat: Lottie 대신 CSS 기반 로딩 스피너로 교체
  package.json
  pnpm-lock.yaml
  public/loading/lion.json
  src/app/_component/common/Spinner.module.css
  src/app/_component/common/Spinner.tsx
  src/app/_component/domain/addarticle/AddArticleModal.tsx
  src/app/_component/domain/main/StudySection.module.css
  src/app/_component/domain/main/StudySection.tsx
  src/app/loading.tsx
  src/lib/lottieLion.ts
Labels: 🎨Style, 🐞Bug

#83 Style : 스터디룸 유효성 검사 버그 수정 및 스터디룸 레이아웃 개선
  src/app/_component/studyroom/CommonStyles.module.css
  src/app/_component/studyroom/StudyroomMain.tsx
  src/app/_component/studyroom/StudyroomTitle.module.css
  src/app/styles/not-found.module.css
Labels: 🎨Style, 🐞Bug

#84 Refactor/markdown editor
  package.json
  pnpm-lock.yaml
  src/app/(non-topbar-layout)/addarticle/page.tsx
  src/app/(non-topbar-layout)/article/[id]/page.tsx
  src/app/_component/domain/addarticle/ToastEditor.tsx
  src/app/_component/domain/readArticle/ArticleContent.module.css
  src/app/_component/domain/readArticle/ArticleContent.tsx
  src/app/_component/domain/readArticle/ArticleList.module.css
  src/app/_component/domain/readArticle/ArticleList.tsx
  src/app/_component/domain/readArticle/ArticleMain.module.css
  src/app/_component/domain/readArticle/ArticleMain.tsx
  src/app/_component/domain/readArticle/Comment.module.css
  src/app/_component/domain/readArticle/Comment.tsx
  src/app/_component/studyroom/Article.tsx
Labels: 💡Feature, 🎨Style, 🛠️Refactor

#88 Refactor : articleroom layout 수정
  src/app/_component/studyroom/AddSubContentBtn.tsx
  src/app/_component/studyroom/Article.module.css
  src/app/_component/studyroom/Article.tsx
  src/app/_component/studyroom/CommonStyles.module.css
  src/app/_component/studyroom/Notice.module.css
  src/app/_component/studyroom/Notice.tsx
  src/app/_component/studyroom/StudyroomMain.module.css
  src/app/_component/studyroom/StudyroomMain.tsx
  src/app/_component/studyroom/StudyroomTitle.module.css
  src/app/_component/studyroom/StudyroomTitle.tsx
  src/assets/icon/clip.svg
  src/assets/image/babyLion.png
  src/assets/image/bigLion.png
Labels: 🎨Style, 🛠️Refactor

#91 Feat: 아티클 본문 ui 퍼블리싱
  src/app/_component/domain/readArticle/ArticleContent.module.css
  src/app/_component/domain/readArticle/ArticleContent.tsx
  src/app/_component/domain/readArticle/ArticleMain.module.css
  src/app/_component/domain/readArticle/ArticleMain.tsx
  src/app/_component/domain/readArticle/Reference.module.css
  src/app/_component/domain/readArticle/Reference.tsx
  src/assets/icon/menu.svg
  src/assets/image/urlImage.png
Labels: 💡Feature

#92 Feat : articleroom의 페이지네이션 적용, 레이아웃 수정 마무리
  src/app/_component/domain/main/StudyBtn.module.css
  src/app/_component/studyroom/AddSubContentBtn.tsx
  src/app/_component/studyroom/Article.module.css
  src/app/_component/studyroom/Article.tsx
  src/app/_component/studyroom/CommonStyles.module.css
  src/app/_component/studyroom/Link.module.css
  src/app/_component/studyroom/Link.tsx
  src/app/_component/studyroom/Notice.module.css
  src/app/_component/studyroom/Notice.tsx
  src/app/_component/studyroom/StudyroomTitle.module.css
  src/app/_component/studyroom/StudyroomTitle.tsx
  src/app/_component/studyroom/modal/AddLinkContentModal.tsx
  src/app/_component/studyroom/modal/AddNoticeContentModal.tsx
  src/app/_component/studyroom/modal/DeleteContentModal.tsx
  src/assets/icon/alarm.svg
  src/assets/icon/arrow_bottom.svg
  src/assets/icon/arrow_top.svg
  src/assets/icon/trash.svg
  src/constants/StudyroomContentType.ts
  src/hooks/useLinks.ts
  src/hooks/useNotices.ts
  src/types/studyRoomDetails/link.ts
  src/types/studyRoomDetails/notice.ts
Labels: 💡Feature, 🎨Style

#97 Feat: 아티클 본문 및 작성 페이지 모달 추가
  src/app/_component/domain/addarticle/AddArticleMain.module.css
  src/app/_component/domain/addarticle/InfoModal.module.css
  src/app/_component/domain/addarticle/InfoModal.tsx
  src/app/_component/domain/addarticle/MarkdownEditor.module.css
  src/app/_component/domain/addarticle/TopBtnContainer.module.css
  src/app/_component/domain/addarticle/TopBtnContainer.tsx
  src/app/_component/domain/readArticle/ArticleContent.tsx
  src/app/_component/domain/readArticle/MenuModal.module.css
  src/app/_component/domain/readArticle/MenuModal.tsx
  src/app/_component/domain/readArticle/ReadArticleModal.module.css
  src/app/_component/domain/readArticle/ReadArticleModal.tsx
  src/app/_component/studyroom/modal/DeleteContentModal.tsx
  src/assets/icon/pencil.svg
  src/assets/icon/trash.svg
  src/assets/icon/trash_black.svg
  src/constants/markdownGuide.ts
Labels: 💡Feature

#100 Feat: 댓글 기능 구현
  src/app/_component/domain/readArticle/ArticleMain.tsx
  src/app/_component/domain/readArticle/Comment.module.css
  src/app/_component/domain/readArticle/Comment.tsx
  src/assets/icon/download.svg
  src/assets/icon/file.svg
  src/assets/icon/gray_delete.svg
  src/assets/icon/upload_arrow.svg
Labels: 💡Feature

#101 feat : articleList 구현 및 studyroomId 유효성 검증 방식 변경, 스타일링 수정
  src/app/(non-topbar-layout)/studyroom/[id]/article/[articleId]/page.tsx
  src/app/(non-topbar-layout)/studyroom/[id]/layout.tsx
  src/app/(non-topbar-layout)/studyroom/[id]/page.tsx
  src/app/_component/domain/readArticle/ArticleList.module.css
  src/app/_component/domain/readArticle/ArticleList.tsx
  src/app/_component/domain/readArticle/ArticleMain.module.css
  src/app/_component/domain/readArticle/ArticleMain.tsx
  src/app/_component/studyroom/Article.module.css
  src/app/_component/studyroom/Article.tsx
  src/app/_component/studyroom/ClientStudyroomIdSetter.tsx
  src/app/_component/studyroom/CommonStyles.module.css
  src/app/_component/studyroom/Notice.tsx
  src/app/_component/studyroom/StudyroomMain.tsx
  src/app/_component/studyroom/StudyroomTitle.tsx
  src/assets/icon/triangle.svg
  src/lib/studyroom.ts
  src/store/useArticleIdStore.ts
Labels: 💡Feature, 🎨Style, 🛠️Refactor

#103 Refactor: 로딩 상태 개선 및 pagination 시 scroll 이동
  src/app/_component/studyroom/Article.tsx
  src/app/_component/studyroom/Notice.tsx
  src/app/_component/studyroom/StudyroomMain.tsx
  src/app/_component/studyroom/StudyroomTitle.tsx
Labels: 🛠️Refactor

#104 Refactor: 댓글 작업 리팩토링
  src/app/_component/domain/readArticle/ArticleMain.tsx
  src/app/_component/domain/readArticle/Comment.module.css
  src/app/_component/domain/readArticle/Comment.tsx
  src/constants/ToastTypeList.ts
  src/utils/convertUrlsToLinks.tsx
Labels: 🎨Style, 🛠️Refactor

#105 Feat: 태그 생성, 추가, 삭제
  src/app/_component/domain/addarticle/AddArticleMain.tsx
  src/app/_component/domain/addarticle/AddTag.module.css
  src/app/_component/domain/addarticle/AddTag.tsx
  src/app/_component/domain/addarticle/DeleteModal.tsx
  src/app/_component/domain/addarticle/Modal/AddTagModal.module.css
  src/app/_component/domain/addarticle/Modal/AddTagModal.tsx
  src/app/_component/domain/login/modal/SignUpModalContent.tsx
  src/app/_component/domain/readArticle/ArticleContent.module.css
  src/app/_component/domain/readArticle/MenuModal.module.css
  src/constants/PartDefaultTag.ts
  src/constants/TagColors.ts
  src/constants/ToastTypeList.ts
  src/hooks/useArticleSubmit.ts
  src/hooks/useDraftLoader.ts
  src/hooks/useTagHandler.ts
  src/store/useUserStore.ts
Labels: 💡Feature

#107 Fix: 태그 새로고침 적용 오류 해결
  src/app/_component/domain/addarticle/AddTag.tsx
  src/app/_component/domain/addarticle/Modal/AddTagModal.tsx
  src/constants/PartDefaultTag.ts
Labels: 🐞Bug

#112 Fix: 아티클 수정하기 원문 불러오기 및 태그 작업
  src/app/_component/common/Toast.module.css
  src/app/_component/domain/addarticle/AddArticleMain.module.css
  src/app/_component/domain/addarticle/AddArticleMain.tsx
  src/app/_component/domain/addarticle/AddTag.module.css
  src/app/_component/domain/addarticle/AddTag.tsx
  src/app/_component/domain/addarticle/MarkdownEditor.module.css
  src/app/_component/domain/addarticle/MarkdownEditor.tsx
  src/app/_component/domain/addarticle/Modal/AddTagModal.module.css
  src/app/_component/domain/addarticle/Modal/AddTagModal.tsx
  src/app/_component/domain/addarticle/Modal/DeleteModal.module.css
  src/app/_component/domain/addarticle/Modal/DeleteModal.tsx
  src/app/_component/domain/addarticle/Modal/InfoModal.module.css
  src/app/_component/domain/addarticle/Modal/InfoModal.tsx
  src/app/_component/domain/addarticle/Modal/TempSubmitModal.tsx
  src/app/_component/domain/addarticle/Titlebox.module.css
  src/app/_component/domain/addarticle/TopBtnContainer.module.css
  src/app/_component/domain/addarticle/TopBtnContainer.tsx
  src/assets/icon/plus_tag.svg
  src/assets/icon/plus_tag_add.svg
  src/constants/ToastTypeList.ts
Labels: 🛠️Refactor, 🐞Bug

#115 Feat : 아티클 데이터 전역 처리 및 tag 렌더
  src/app/(non-topbar-layout)/studyroom/[id]/layout.tsx
  src/app/_component/common/TagItem.module.css
  src/app/_component/common/TagItem.tsx
  src/app/_component/domain/readArticle/ArticleContent.module.css
  src/app/_component/domain/readArticle/ArticleContent.tsx
  src/app/_component/domain/readArticle/ArticleList.tsx
  src/app/_component/domain/readArticle/ArticleMain.tsx
  src/app/_component/studyroom/Article.tsx
  src/app/_component/studyroom/ClientStudyroomIdSetter.tsx
  src/app/_component/studyroom/StudyroomMain.tsx
  src/app/_component/studyroom/modal/DeleteContentModal.tsx
  src/hooks/useArticles.ts
  src/store/useArticlesStore.ts
  src/types/studyRoomDetails/article.ts
Labels: 💡Feature, 🛠️Refactor

#121 Fix: Firebase Storage 파일 다운로드 CORS 에러 해결
  src/app/_component/domain/readArticle/Comment.tsx
Labels: 🐞Bug

#126 Style: 스타일 수정사항 반영
  src/app/_component/common/TagItem.module.css
  src/app/_component/domain/addarticle/modal/AddTagModal.module.css
  src/app/_component/studyroom/Article.module.css
  src/app/_component/studyroom/Article.tsx
Labels: 🎨Style

#130 fix: 링크 현재 탭에서 열리는 문제 해결 및 스타일 수정
  src/app/_component/domain/addarticle/MarkdownEditor.tsx
  src/app/_component/domain/addarticle/modal/LinkModal.module.css
  src/app/_component/domain/readArticle/ArticleContent.module.css
  src/app/_component/domain/readArticle/ArticleContent.tsx
  src/app/_component/domain/readArticle/Reference.module.css
Labels: 🛠️Refactor, 🐞Bug

#134 refactor : 404 깜빡임 해결, 이미지 경로 preview에서 제거, 스타일 수정 및 수정사항 반영
  src/app/_component/domain/readArticle/ArticleMain.tsx
  src/app/_component/studyroom/Article.module.css
  src/app/_component/studyroom/modal/AddNoticeContentModal.tsx
  src/store/useArticlesStore.ts
Labels: 🎨Style, 🛠️Refactor, 🐞Bug

#136 refactor: reference api 성능 개선 및 ol, ul 렌더링 안되는 이슈
  src/app/_component/domain/addarticle/AddArticleMain.tsx
  src/app/_component/domain/addarticle/MarkdownEditor.tsx
  src/app/_component/domain/readArticle/ArticleContent.tsx
  src/app/_component/domain/readArticle/Reference.tsx
  src/hooks/useArticleSubmit.ts
  src/hooks/useFetchMicroLink.ts
  src/types/articles/microlink.ts
Labels: 🛠️Refactor, 🐞Bug

#138 Fix: 댓글 섹션 스크롤 기본 위치를 맨 아래로 설정 및 댓글 중복 입력 방지
  src/app/_component/domain/readArticle/Comment.tsx
Labels: 💡Feature

#139 Feat: Vercel Analytics 추가
  package.json
  pnpm-lock.yaml
  src/app/layout.tsx
Labels: 💡Feature

#141 🤖chore: 의존성 배열 수정
  src/app/_component/domain/readArticle/ArticleMain.tsx
  src/app/_component/studyroom/modal/DeleteContentModal.tsx
Labels: 🐞Bug

#142 refactor: 태그 색상 랜덤 생성 및 아티클 작성 후 페이지 이동
  src/app/_component/domain/addarticle/AddArticleMain.tsx
  src/app/_component/domain/addarticle/AddTag.tsx
  src/app/_component/domain/readArticle/ArticleContent.module.css
  src/app/styles/globals.css
  src/constants/TagColors.ts
  src/hooks/useArticleSubmit.ts
  src/hooks/useRandomColor.ts
  src/hooks/useTagHandler.ts
Labels: 🎨Style, 🛠️Refactor

#149 Refactor : commonTag fetch 최적화 및 이미지 최적화
  src/app/_component/domain/readArticle/ArticleContent.tsx
  src/app/_component/domain/readArticle/ArticleMain.tsx
  src/app/_component/studyroom/Article.module.css
  src/app/_component/studyroom/Article.tsx
  src/app/_component/studyroom/ClientStudyroomIdSetter.tsx
  src/hooks/useTagHandler.ts
  src/store/useCommontagStore.ts
Labels: 🛠️Refactor

#151 Refactor: 메인 페이지 스터디룸 로직 커스텀 훅으로 분리 및 폴더 구조, 훅 폴더 정리
  src/app/(common-layout)/members/page.module.css
  src/app/(common-layout)/members/page.tsx
  src/app/(common-layout)/page.module.css
  src/app/(common-layout)/page.tsx
  src/app/_component/common/Modal.tsx
  src/app/_component/domain/addarticle/AddArticleMain.tsx
  src/app/_component/domain/addarticle/MarkdownEditor.tsx
  src/app/_component/domain/addarticle/modal/LinkModal.tsx
  src/app/_component/domain/login/GoogleLoginBtn.tsx
  src/app/_component/domain/login/NameBtn.tsx
  src/app/_component/domain/login/UserBtn.tsx
  src/app/_component/domain/main/AddStudyContent.tsx
  src/app/_component/domain/main/StudyBtn.tsx
  src/app/_component/domain/main/StudySection.tsx
  src/app/_component/domain/readArticle/ArticleContent.tsx
  src/app/_component/domain/readArticle/ArticleList.tsx
  src/app/_component/studyroom/Article.tsx
  src/app/_component/studyroom/Notice.tsx
  src/app/_component/studyroom/StudyroomMain.tsx
  src/app/_component/studyroom/StudyroomTitle.tsx
  src/app/_component/studyroom/modal/AddNoticeContentModal.tsx
  src/app/_component/studyroom/modal/DeleteContentModal.tsx
  src/hooks/article/index.ts
  src/hooks/article/useArticleSubmit.ts
  src/hooks/article/useDraftLoader.ts
  src/hooks/article/useNotices.ts
  src/hooks/auth/index.ts
  src/hooks/auth/useAuth.ts
  src/hooks/auth/useHydration.ts
  src/hooks/common/index.ts
  src/hooks/common/useConfirmBeforeRefresh.ts
  src/hooks/index.ts
  src/hooks/microLink/index.ts
  src/hooks/microLink/useContentExtract.ts
  src/hooks/microLink/useFetchMicroLink.ts
  src/hooks/microLink/useMicroLink.ts
  src/hooks/studyroom/index.ts
  src/hooks/studyroom/useFavorite.ts
  src/hooks/studyroom/useStudyRooms.ts
  src/hooks/studyroom/useStudyroomDetail.ts
  src/hooks/ui/index.ts
  src/hooks/ui/useIsMounted.ts
  src/hooks/ui/useRandomColor.ts
  src/hooks/ui/useTagHandler.ts
Labels: 🛠️Refactor
